apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-volume-claim
  labels:
    app: nginx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: storage-class
  resources:
    requests:
      storage: 100Mi